### ISSUE TITLE
mechanize._response.httperror_seek_wrapper: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by egyjs** [FDX100/GOD-Force#1]
error in proxy
this is the out but : 
```python
[GOD#] >>> now your using this ip  :176.10.99.200
Traceback (most recent call last):
  File "GOD-force.py", line 160, in <module>
    br.open(website)
  File "/usr/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 203, in open
    return self._mech_open(url, data, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 255, in _mech_open
    raise response
mechanize._response.httperror_seek_wrapper: HTTP Error 403: Forbidden

```

**Comment by egyjs** [comment]
You should use another proxy 
> Tor is much easier to block than other open proxies since the list of exit IP addresses is known and published   : https://stackoverflow.com/a/9861102/7511165

Have a look for alternative here: https://www.maketecheasier.com/tor-alternatives-for-anonymous-browsing/

**Comment by Omar1111111y** [comment]
واذا كانت انا حدث معي هذا الخطا اريد الحل
